categories: [Visualization]
description: A tool to create a UCSC track hub
name: hubarchivecreator
owner: remimarenco
remote_repository_url: https://github.com/goeckslab/hub-archive-creator
exclude:
  - hubaDataType
  - tool_test_output.html
  - tool_test_output.json
  - test-data
  - tools

