#!/usr/bin/env bash

localBinPath="/usr/local/bin/"
hgDownloadURl="http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/"

# Binaries needed for HAC
twoBitInfo="twoBitInfo"
faToTwoBit="faToTwoBit"
gff3ToGenePred="gff3ToGenePred"
gtfToGenePred="gtfToGenePred"
genePredToBed="genePredToBed"
# sort="sort"
bedToBigBed="bedToBigBed"

binariesArray=( ${twoBitInfo} ${faToTwoBit} ${gff3ToGenePred} ${gtfToGenePred} ${genePredToBed} ${bedToBigBed} )

# Download and install binaries
for binaryName in "${binariesArray[@]}"
do
    binaryInstallationPath="${localBinPath}/${binaryName}"
    sudo wget -P ${localBinPath} "${hgDownloadURl}/${binaryName}"
    sudo chown ${USER} ${binaryInstallationPath}
    sudo chmod +x ${binaryInstallationPath}
done
